### ISSUE TITLE
Driver of Pmod-VGA

### ISSUE THREAD

**Issue by L0stMyN4me** [Digilent/Arty-A7-100-Pmod-VGA#4]
We can not find the information for driver file of Pmod-VGA,there is no file in Digilent/vivado-library.
Could you please provide the driver file of Pmod-VGA?
Thank you!

**Comment by artvvb** [comment]
Digilent doesn't provide a Pmod IP core for the Pmod VGA or any demos for it specific to use with a Microblaze or Zynq processor. Several demos exist for different boards which make use of it (though note all three of these are largely the same):
- https://digilent.com/reference/programmable-logic/arty-a7/demos/pmod-vga
- https://digilent.com/reference/programmable-logic/cora-z7/demos/pmod-vga
- https://digilent.com/reference/programmable-logic/zybo-z7/demos/pmod-vga

Thanks,
Arthur
